### ISSUE TITLE
Segmentation fault on macOS Mojave

### ISSUE THREAD

**Issue by TommasoBendinelli** [caltechlibrary/handprint#16]
(env) tommasos-mbp:TestHandwriting tommaso$ handprint -s amazon-textract test-1.png 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃    Welcome to Handprint, the Handwritten page recognition test!    ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Will apply 1 service (amazon-textract) to 1 image.
Will use up to 2 process threads.
Starting on test-1.png
Sending to amazon-textract and waiting for response ...
Got result from amazon-textract.
Creating annotated image for amazon-textract.
/Users/tommaso/Documents/Code/CSEM_repos/TestHandwriting/env/lib/python3.7/site-packages/handprint/images.py:218: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, axes = plt.subplots(nrows = 1, ncols = 1, figsize = (20, 20))
2020-08-05 15:02:36.591 Python[2255:77879] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
2020-08-05 15:02:36.623 Python[2255:77879] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff381f8a7d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff628caa17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff382125d9 -[NSException raise] + 9
	3   AppKit                              0x00007fff357b85ca -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 317
	4   AppKit                              0x00007fff357b59f7 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
	5   AppKit                              0x00007fff357b542a -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	6   _macosx.cpython-37m-darwin.so       0x0000000116d7cc40 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 80
	7   _macosx.cpython-37m-darwin.so       0x0000000116d808b4 FigureManager_init + 292
	8   Python                              0x000000010bf1df30 wrap_init + 12
	9   Python                              0x000000010bee589d wrapperdescr_call + 337
	10  Python                              0x000000010bedfc46 _PyObject_FastCallKeywords + 358
	11  Python                              0x000000010bf75322 call_function + 730
	12  Python                              0x000000010bf6e297 _PyEval_EvalFrameDefault + 6767
	13  Python                              0x000000010bee01a4 function_code_fastcall + 106
	14  Python                              0x000000010bee0b17 _PyObject_Call_Prepend + 131
	15  Python                              0x000000010bf1de9e slot_tp_init + 80
	16  Python                              0x000000010bf1abca type_call + 172
	17  Python                              0x000000010bedfc46 _PyObject_FastCallKeywords + 358
	18  Python                              0x000000010bf75322 call_function + 730
	19  Python                              0x000000010bf6e297 _PyEval_EvalFrameDefault + 6767
	20  Python                              0x000000010bee01a4 function_code_fastcall + 106
	21  Python                              0x000000010bf75329 call_function + 737
	22  Python                              0x000000010bf6e297 _PyEval_EvalFrameDefault + 6767
	23  Python                              0x000000010bf75b1d _PyEval_EvalCodeWithName + 1698
	24  Python                              0x000000010bedfa10 _PyFunction_FastCallDict + 444
	25  Python                              0x000000010bee0b17 _PyObject_Call_Prepend + 131
	26  Python                              0x000000010bedfedd PyObject_Call + 136
	27  Python                              0x000000010bf6e57b _PyEval_EvalFrameDefault + 7507
	28  Python                              0x000000010bf75b1d _PyEval_EvalCodeWithName + 1698
	29  Python                              0x000000010bedfa10 _PyFunction_FastCallDict + 444
	30  Python                              0x000000010bf6e57b _PyEval_EvalFrameDefault + 7507
	31  Python                              0x000000010bf75b1d _PyEval_EvalCodeWithName + 1698
	32  Python                              0x000000010bedfa10 _PyFunction_FastCallDict + 444
	33  Python                              0x000000010bf6e57b _PyEval_EvalFrameDefault + 7507
	34  Python                              0x000000010bf75b1d _PyEval_EvalCodeWithName + 1698
	35  Python                              0x000000010bedfa10 _PyFunction_FastCallDict + 444
	36  Python                              0x000000010bf6e57b _PyEval_EvalFrameDefault + 7507
	37  Python                              0x000000010bf75b1d _PyEval_EvalCodeWithName + 1698
	38  Python                              0x000000010bedfd98 _PyFunction_FastCallKeywords + 212
	39  Python                              0x000000010bf75329 call_function + 737
	40  Python                              0x000000010bf6e3da _PyEval_EvalFrameDefault + 7090
	41  Python                              0x000000010bf75b1d _PyEval_EvalCodeWithName + 1698
	42  Python                              0x000000010bedfd98 _PyFunction_FastCallKeywords + 212
	43  Python                              0x000000010bf75329 call_function + 737
	44  Python                              0x000000010bf6e332 _PyEval_EvalFrameDefault + 6922
	45  Python                              0x000000010bee01a4 function_code_fastcall + 106
	46  Python                              0x000000010bee0b17 _PyObject_Call_Prepend + 131
	47  Python                              0x000000010bedfedd PyObject_Call + 136
	48  Python                              0x000000010bf6e57b _PyEval_EvalFrameDefault + 7507
	49  Python                              0x000000010bee01a4 function_code_fastcall + 106
	50  Python                              0x000000010bf75329 call_function + 737
	51  Python                              0x000000010bf6e27e _PyEval_EvalFrameDefault + 6742
	52  Python                              0x000000010bee01a4 function_code_fastcall + 106
	53  Python                              0x000000010bf6e57b _PyEval_EvalFrameDefault + 7507
	54  Python                              0x000000010bee01a4 function_code_fastcall + 106
	55  Python                              0x000000010bf75329 call_function + 737
	56  Python                              0x000000010bf6e27e _PyEval_EvalFrameDefault + 6742
	57  Python                              0x000000010bee01a4 function_code_fastcall + 106
	58  Python                              0x000000010bf75329 call_function + 737
	59  Python                              0x000000010bf6e27e _PyEval_EvalFrameDefault + 6742
	60  Python                              0x000000010bee01a4 function_code_fastcall + 106
	61  Python                              0x000000010bee0b17 _PyObject_Call_Prepend + 131
	62  Python                              0x000000010bedfedd PyObject_Call + 136
	63  Python                              0x000000010bfdbd01 t_bootstrap + 71
	64  Python                              0x000000010bfa30be pythread_wrapper + 25
	65  libsystem_pthread.dylib             0x00007fff6428c2eb _pthread_body + 126
	66  libsystem_pthread.dylib             0x00007fff6428f249 _pthread_start + 66
	67  libsystem_pthread.dylib             0x00007fff6428b40d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by mhucka** [comment]
Thanks for the report. As a quick guess, this looks like an issue with macos window interaction in matplotlib. I don't have Mojave installed anywhere so I can't test and investigate it immediately. I will have to set up a virtual machine for Mojave – something I've been meaning to do anyway.

**Comment by mhucka** [comment]
This should be fixed in version 1.3.0 of Handprint, coming up shortly.
