### ISSUE TITLE
'handprint/methods' does not exist

### ISSUE THREAD

**Issue by syed-9909** [caltechlibrary/handprint#8]
While installing on Windows getting error:
D:\OCR\handprint-0.10.0\handprint-0.10.0>py -m pip install . --upgrade
Processing d:\ocr\handprint-0.10.0\handprint-0.10.0
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info\handprint.egg-info
    writing pip-egg-info\handprint.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\handprint.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\handprint.egg-info\requires.txt
    writing top-level names to pip-egg-info\handprint.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\handprint.egg-info\SOURCES.txt'
    error: package directory 'handprint/methods' does not exist
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-req-build-kebkz6bp\
WARNING: You are using pip version 19.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by mhucka** [comment]
Thanks for the report, and my apologies for the trouble. I'll take a look at the Windows installation, but in the meantime, I wanted to mention I'm just about to release a new version – a full version 1.0.0 with a number of changes and (hopefully) improvements. This will happen this week.

**Comment by mhucka** [comment]
This is fixed in commit d690ab87ece7ddb33080fd3913fc2240cba8cd98 in branch `develop`. The README for `develop` is not properly up to date with the new changes, however.

**Comment by mhucka** [comment]
This should be fixed in version 1.0.0, just released. Thank you again for this report. I'm going to close this issue now/
