### ISSUE TITLE
Credentials files are not saved in expected format on Windows

### ISSUE THREAD

**Issue by criley10** [caltechlibrary/handprint#9]
The credentials files are copied to C:\Users\<username>\AppData\Local\Handprint\Handprint but are not renamed to the filenames expected for credentials. Once the files are renamed to amazon_credentials.json or microsoft_credentials.json and readded using /a commands will run properly. 

Tested with AWS and Microsoft credentials, but I believe this is caused by the process used to copy credentials and not the individual service credential classes. 

Only confirmed on Windows.

**Comment by mhucka** [comment]
Thank you very much for this report. This should be now fixed in release 1.0.3.
